# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Exploring Noh Theater
email: tbd@tbd.com
description: >- # this means to ignore newlines until "baseurl:"
  An interactive, intermedia analysis of Noh Theater.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
source: src
markdown: kramdown
# theme: minima

# Collection settings
collections:
  hashitomi:
    output: true
    permalink: /:collection/:path/
  kokaji:
    output: true
    permalink: /:collection/:path/
  plays:
    output: true
    permalink: /:path/
  libretti:
    output: true
    permalink: /:path/
  music:
    output: true
    permalink: /:collection/:path/
  movement:
    output: true
    permalink: /:collection/:path/
  catalog-of-shodan:
    output: true
    permalink: /:collection/:path/


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# required for Travis: https://jekyllrb.com/docs/continuous-integration/travis-ci/
exclude: [vendor]

plugins:
  - jekyll-autoprefixer